import FiturPage from "@/module/fitur";


export const metadata = {
  title: "Rawat ID | Fitur Unggulan",
  description: "Generated by create next app",
};

export default function page() {
  return <FiturPage />;
}
