import BlogPage from "@/module/blog";

export const metadata = {
  title: "Rawat ID | Blog",
  description: "Generated by create next app",
};

export default function page() {
  return <BlogPage />;
}
