import RegistrasiPage from "@/module/register";


export const metadata = {
  title: "Rawat ID | Registrasi",
  description: "Generated by create next app",
};

export default function page() {
  return <RegistrasiPage />;
}
